from worlds.drehmal.item.item_manager import needed, useful_unique, filler, trap, needed_bl, blank_filler

drehmal_mythicals = [
    useful_unique("Ascendance"),
    useful_unique("Calamity"),
    useful_unique("Frenzy"),
    useful_unique("Malevolentia"),
    needed("Inert Mythbreaker"),
    useful_unique("True Mythbreaker"),
    useful_unique("Oblivion"),
    useful_unique("Syzygy"),
    useful_unique("Zenith")
]

drehmal_legendaries = [
    useful_unique("Aeongale"),
    useful_unique("AvPod"),
    needed("Avsohm'Kohl"),
    useful_unique("Crystal Digging Claws"),
    useful_unique("Eldermead"),
    useful_unique("Emperor Anyr's Scepter"),
    needed("Eyebiter"),
    useful_unique("Festering Strides"),
    useful_unique("Flammer"),
    useful_unique("The Frostfang"),
    useful_unique("The Heartaxe"),
    useful_unique("Hovadchear's Greathammer"),
    useful_unique("Magestep"),
    useful_unique("Masayoshi"),
    useful_unique("One Thousand Scars"),
    useful_unique("Orchidaceae"),
    useful_unique("Osteogenesis"),
    useful_unique("Parenchyma"),
    useful_unique("Peace Treaty"),
    useful_unique("Penumbra"),
    useful_unique("Proxigea"),
    useful_unique("Pure Corruption"),
    useful_unique("Rehntite Plate Mail"),
    useful_unique("Stasis Bolts"),
    useful_unique("Thundercrux"),
    useful_unique("Tul'Vohaln"),
    useful_unique("Ultva's Bowblade"),
    useful_unique("Voidtear Dagger"),
    needed("Warp Horse Armor"),
    needed("Warp Horse Receiver"),
    useful_unique("Whispersong")
]

drehmal_terminus_towers = [
    needed("Akhlo'Rohma Tower"),
    needed("Anyr'Nogur Tower"),
    needed("Aphelion Tower"),
    needed("Av'Sal Tower"),
    needed("Black Jungle Tower"),
    needed("Carmine Tower"),
    needed("Casai Tower"),
    needed("Island of Dawn Tower"),
    needed("Island of Dusk Tower"),
    needed("Mt. Ebonfire Tower"),
    needed("Ebony Veldt Tower"),
    needed("Faehrcyle Tower"),
    needed("Frozen Bite Tower"),
    needed("Grand Pike Canyon Tower"),
    needed("Gulf of Drehmal Tower"),
    needed("North Heartwood Tower"),
    needed("Hellcrags Tower"),
    needed("Highfall Tundra Tower"),
    needed("Lo'Dahr Tower"),
    needed("Lorahn'Kahl Tower"),
    needed("South Heartwood Tower"),
    needed("Merijool Tower"),
    needed("Nimahj Swamp Tower"),
    needed("North Tharxax Tower"),
    needed("Palisades Heath Tower"),
    needed("Purity Peaks Tower"),
    needed("Sahd Tower"),
    needed("South Tharxax Tower"),
    needed("Spearhead Forest Tower"),
    needed("Veruhkt Plateau Tower"),
    needed("Yavhlix Tower")
]

drehmal_quest_items = [
    needed("Left Blade Fragment"),
    needed("Right Blade Fragment"),
    needed("Fragment of Fury"),
    needed("Fragment of Hate"),
    needed("Fragment of Pain"),
    needed("Fragment of Rage"),
    needed("Fragment of Wrath"),
    needed("Nihilist's Notes"),
    useful_unique("Stone of Agony"),
    useful_unique("Stone of Luxury"),
    useful_unique("Stone of Worry"),
    needed("Yavhlix Lever 1"),
    needed("Yavhlix Lever 2"),
    needed("Yavhlix Lever 3"),
    needed("Duplicate Yavhlix Lever"),
    needed("Foundry Lever 1"),
    needed("Foundry Lever 2"),
    needed("Foundry Lever 3"),
    useful_unique("Tank Keyfob")
]

drehmal_relics = [
    useful_unique("Writ of Authority +0"),
    useful_unique("Writ of Authority +1"),
    useful_unique("Writ of Authority +2"),
    useful_unique("Writ of Authority +3"),
    useful_unique("Effloresce +0"),
    useful_unique("Effloresce +1"),
    useful_unique("Effloresce +2"),
    useful_unique("Effloresce +3"),
    useful_unique("Mysterial +0"),
    useful_unique("Mysterial +1"),
    useful_unique("Mysterial +2"),
    useful_unique("Mysterial +3"),
    useful_unique("Ardorbrand +0"),
    useful_unique("Ardorbrand +1"),
    useful_unique("Ardorbrand +2"),
    useful_unique("Ardorbrand +3"),
    useful_unique("Cryostatic +0"),
    useful_unique("Cryostatic +1"),
    useful_unique("Cryostatic +2"),
    useful_unique("Cryostatic +3"),
    useful_unique("Sprout of Anguish +0"),
    useful_unique("Sprout of Anguish +1"),
    useful_unique("Sprout of Anguish +2"),
    useful_unique("Sprout of Anguish +3"),
    useful_unique("Mirror of Frailty"),
    useful_unique("Mirror of Lethargy"),
    useful_unique("Mirror of Miasma"),
    useful_unique("Mirror of Entropy"),
    useful_unique("Orogeny +0"),
    useful_unique("Orogeny +1"),
    useful_unique("Orogeny +2"),
    useful_unique("Orogeny +3"),
    useful_unique("Resplendence +0"),
    useful_unique("Resplendence +1"),
    useful_unique("Resplendence +2"),
    useful_unique("Resplendence +3"),
    useful_unique("Purifying Light +0"),
    useful_unique("Purifying Light +1"),
    useful_unique("Purifying Light +2"),
    useful_unique("Purifying Light +3"),
    useful_unique("Mortality +0"),
    useful_unique("Mortality +1"),
    useful_unique("Mortality +2"),
    useful_unique("Mortality +3")
]