# I keep forgetting the values, so now there's constants for them...

# ADVANCEMENT

ADVANCEMENT = 0
ADVANCEMENT_HARD = 1
ADVANCEMENT_EXPLORATION = 2
ADVANCEMENT_UNREASONABLE = 3

# DREHMAL

MYTHICALS = 100
LEGENDARIES = 101
TERMINUS_TOWERS = 102
QUEST_ITEMS = 103
RELICS = 104