drehmal_legendaries = [
    "Aeongale",
    "AvPod",
    "Avsohm'Kohl",
    "Crystal Digging Claws",
    "Eldermead",
    "Emperor Anyr's Scepter",
    "Eyebiter",
    "Festering Strides",
    "Flammer",
    "The Frostfang",
    "The Heartaxe",
    "Hovadchear's Greathammer",
    "Magestep",
    "Masayoshi",
    "One Thousand Scars",
    "Orchidaceae",
    "Osteogenesis",
    "Parenchyma",
    "Peace Treaty",
    "Penumbra",
    "Proxigea",
    "Pure Corruption",
    "Rehntite Plate Mail",
    "Stasis Bolts",
    "Thundercrux",
    "Tul'Vohaln",
    "Ultva's Bowblade",
    "Voidtear Dagger",
    "Warp Horse Armor",
    "Warp Horse Receiver",
    "Whispersong"
]