drehmal_relics = [
    "Writ of Authority +0",
    "Writ of Authority +1",
    "Writ of Authority +2",
    "Writ of Authority +3",
    "Effloresce +0",
    "Effloresce +1",
    "Effloresce +2",
    "Effloresce +3",
    "Mysterial +0",
    "Mysterial +1",
    "Mysterial +2",
    "Mysterial +3",
    "Ardorbrand +0",
    "Ardorbrand +1",
    "Ardorbrand +2",
    "Ardorbrand +3",
    "Cryostatic +0",
    "Cryostatic +1",
    "Cryostatic +2",
    "Cryostatic +3",
    "Sprout of Anguish +0",
    "Sprout of Anguish +1",
    "Sprout of Anguish +2",
    "Sprout of Anguish +3",
    "Mirror of Frailty",
    "Mirror of Lethargy",
    "Mirror of Miasma",
    "Mirror of Entropy",
    "Orogeny +0",
    "Orogeny +1",
    "Orogeny +2",
    "Orogeny +3",
    "Resplendence +0",
    "Resplendence +1",
    "Resplendence +2",
    "Resplendence +3",
    "Purifying Light +0",
    "Purifying Light +1",
    "Purifying Light +2",
    "Purifying Light +3",
    "Mortality +0",
    "Mortality +1",
    "Mortality +2",
    "Mortality +3"
]