drehmal_quest_items = [
   "Ancehl Castle Stone of Agony",
   "Blackstone Ruins Stone of Agony",
   "Burnt Palace Stone of Luxury",
   "Caer Adacia Stone of Worry",
   "Coven of Potentia Stone of Agony",
   "Epicenter of the Desolation Stone of Worry",
   "Fort Aelon Stone of Agony",
   "Foundry Lever 1",
   "Foundry Lever 2",
   "Foundry Lever 3",
   "Foundry Speedrun Stone of Luxury",
   "Fragment of Fury",
   "Fragment of Hate",
   "Fragment of Pain",
   "Fragment of Rage",
   "Fragment of Wrath",
   "Glade of the Giant Stone of Agony",
   "Greyspire Castle Stone of Worry",
   "North Heartwood Stone of Luxury",
   "Oblivion Labyrinth Stone of Worry",
   "Left Blade Fragment",
   "Loraga Keep Stone of Luxury",
   "Naharja Stone of Luxury",
   "Nihilist's Notes",
   "Resonant Halls Stone of Worry",
   "Right Blade Fragment",
   "Sahd Stone of Worry",
   "Sal'Veruhkt Stone of Luxury",
   "Moonlight Sanctum Stone of Agony",
   "Tall Tower Stone of Worry",
   "Tank Keyfob",
   "Tehrmari Monastery Stone of Luxury",
   "Highfall Tundra Ruins Stone of Worry",
   "Xor'huul Stone of Agony",
   "West of Yavhlix Stone of Agony",
   "Yavhlix Lever 1",
   "Yavhlix Lever 2",
   "Yavhlix Lever 3",
   "Zarha Ruins Stone of Luxury"
]