drehmal_terminus_towers = [
    "Akhlo'Rohma Tower",
    "Anyr'Nogur Tower",
    "Aphelion Tower",
    "Av'Sal Tower",
    "Black Jungle Tower",
    "Carmine Tower",
    "Casai Tower",
    "Island of Dawn Tower",
    "Island of Dusk Tower",
    "Mt. Ebonfire Tower",
    "Ebony Veldt Tower",
    "Faehrcyle Tower",
    "Frozen Bite Tower",
    "Grand Pike Canyon Tower",
    "Gulf of Drehmal Tower",
    "North Heartwood Tower",
    "Hellcrags Tower",
    "Highfall Tundra Tower",
    "Lo'Dahr Tower",
    "Lorahn'Kahl Tower",
    "South Heartwood Tower",
    "Merijool Tower",
    "Nimahj Swamp Tower",
    "North Tharxax Tower",
    "Palisades Heath Tower",
    "Purity Peaks Tower",
    "Sahd Tower",
    "South Tharxax Tower",
    "Spearhead Forest Tower",
    "Veruhkt Plateau Tower",
    "Yavhlix Tower"
]