# Vanilla Minecraft Locations
vanilla_advancements = [
    "How Did We Get Here?",
    "A Furious Cocktail",
    "Arbalistic",
    "The Cutest Predator",
    "A Balanced Diet",
    "Two by Two",
    "The Parrots and the Bats",
    "Alchemy",
    "Bullseye",
    "A Complete Catalogue",
    "Bring Home the Asterial Array",
    "Asterial Arrayinator",
    "Necromantic Reversal",
    "Oh Shiny",
    "Runic Magic",
    "Fishy Business",
    "Spooky Scary Skeleton",
    "Drehmari Hero",
    "Sticky Situation",
    "Monster Hunter",
    "Monsters Hunted",
    "The Healing Power of Friendship",
    "Surge Protector",
    "Diamonds!",
    "Serious Dedication",
    "Ol' Betsy",
    "A Seedy Place",
    "Return to Sender",
    "Whatever Floats your Goat!",
    "Bee Our Guest",
    "Cover Me with Diamonds",
    "Take Aim",
    "Total Beelocation",
    "Sweet Dreams",
    "Sniper Duel",
    "Is It a Plane?",
    "Is It a Balloon?",
    "Is It a Bird?",
    "Hired Help",
    "Soulgrafting",
    "Tactical Fishing",
    "Best Friends Forever",
    "Postmortal",
    "What a Deal!",
    "Two Birds, One Arrow",
    "No Place Like Home",
    "Voluntary Exile",
    "Light as a Rabbit",
    "Who's the Mikhmari Now?",

    # Lo'Dahr Advancements
    "Crazy Dragon Lady",
    "BE NOT AFRAID",
    "Otherworldly Expedition",
    "Now You're Thinking With...",
    "The Sky is Falling!",
    "One Small Step",
    "Catching Stars",
    "Local Traditions",
    "Cover Me in Starstuff",
    "Stellar Refuse",
    "Invasive Species",
    "A Gentle Slaughter",
    "Glimpse Into the Cosmos",
    "Survive the Wastes",
    "A Throwaway Joke",
    "Very Very Frightening",
    "Bundled Up",

    # Exploration Advancements
    "Augural Tangle",
    "Upper-Upper Class",
    "I.C.S. Arbiter",
    "Rip & Tear",
    "Supersoldier Certification",
    "Jewel of Casai",
    "Remnant of Avsohm",
    "Vault of Knowledge",
    "Place of Conversion",
    "Challenger's Grotto",
    "The Burnt Palace",
    "All That Remains",
    "Finders Keepers",
    "Ancient Enterprise",
    "Abyssal Rise",
    "This place was beautiful, once",
    "Children of Drehmal",
    "Serpent's Chosen",
    "The Painted City",
    "Children of Mael",
    "City of Tides",
    "The Foundry",
    "People of the Heartwood",
    "Greyspire Castle",
    "Domain of Maelihs",
    "Impoverished Nobles",
    "Grave of Frost",
    "Disappearing Act",
    "Class in Session",
    "What Puzzles Do You Bear?",
    "Secret Sanctum",
    "Mystic Gallery",
    "Pilgrim's Eye",
    "Brightwyrm's Caldarium",
    "The Insohmic Library",
    "Apotheosis",
    "Wall of the West",
    "Lofty Laboratory",
    "Meat. They're made out of meat.",
    "Village of Autumn",
    "Village of Three Moons",
    "I'm on the moooon... it's made of cheeeeese...",
    "Children of Virtuo",
    "The Beast's Den",
    "Distant Lights",
    "Hypogean Labyrinth",
    "The Old Guard",
    "Final Harvest",
    "Avast!",
    "Chamber of Dreams",
    "Glade of the Giant",
    "City of Chaos",
    "The Lost Cavern",
    "A Bridge Between Worlds",
    "Star-Rise Orrery",
    "Put a Ring on it",
    "The Forgotten City",
    "Capital of War",
    "Temporal Ruins",
    "Some Hope For the Future?",
    "The Moonlight Sanctum",
    "The Scarred Castle",
    "Rites of Cruelty",
    "Shatterhorn Gulch",
    "Ash Heap",
    "Ohh, bouncy!",
    "Atop Paradise",
    "Heart of the Tempest",
    "Monastery of Virtuo",
    "Flower Power",
    "Underground Fortress",
    "WUPOM (Wealthy Under Protection of Mael)",
    "Temple of Life",
    "Death's Embrace",
    "If These Walls Could Talk",
    "At the Mountain of Madness",
    "Pantheon",
    "Deja Vu"
]
